AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  webscraperLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: cicd-webscraper
      Description: 'Scrapes events data from a website and places it in DynamoDB'
      Handler: webscraperLambda.lambda_handler
      MemorySize: 128
      Role: 'arn:aws:iam::709303708159:role/service-role/Lambda-DynamoDB-BasicWrite'
      Runtime: python3.6
      Timeout: 30
